name: Windows RDP Direct

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Ativar RDP no Windows
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Instalar Ngrok
        run: |
          choco install ngrok -y

      - name: Autenticar e Iniciar Tunnel RDP
        run: |
          ngrok config add-authtoken SEU_TOKEN_AQUI
          Start-Process -FilePath "ngrok" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 20
          $log = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $publicUrl = $log.tunnels[0].public_url -replace 'tcp://', ''
          Write-Host "=========================================="
          Write-Host "CONECTE NO RD CLIENT USANDO O ENDERECO:"
          Write-Host $publicUrl
          Write-Host "USUARIO: runneradmin"
          Write-Host "=========================================="
          while ($true) { Start-Sleep -Seconds 60 }
