name: Windows RDP Direct

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Instalar Ngrok
        run: |
          choco install ngrok -y

      - name: Autenticar e Iniciar Tunnel RDP
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
          Start-Process -FilePath "ngrok" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 10
          $log = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $publicUrl = $log.tunnels[0].public_url -replace 'tcp://', ''
          Write-Host "=========================================="
          Write-Host "CONECTE NO RD CLIENT USANDO O ENDERECO:"
          Write-Host $publicUrl
          Write-Host "USUARIO: runneradmin"
          Write-Host "=========================================="
          while ($true) { Start-Sleep -Seconds 60 }
